[package]
name = "magnetic-rust"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmm = "0.2.3"
time = "0.3.17"