[package]
name = "rtimu-rust"
version = "0.1.0"
edition = "2021"
description = "RTIMULib2 example"
homepage = "https://github.com/bareboat-necessities/rust-modules/tree/main/RTIMULib2/Linux/rust"

[dependencies]
rtimulib-rust = "0.2.1"
