[package]
name = "lowpass-butterworth-rust"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iir_filters = "0.1.2"
